SET FOREIGN_KEY_CHECKS = 0;

DELETE FROM reservation;
DELETE FROM payment;
DELETE FROM room;
DELETE FROM customer;
DROP TABLE IF EXISTS staff;
DELETE FROM user;

ALTER TABLE reservation AUTO_INCREMENT = 1;
ALTER TABLE payment AUTO_INCREMENT = 1;
ALTER TABLE room AUTO_INCREMENT = 1;
ALTER TABLE customer AUTO_INCREMENT = 1;
ALTER TABLE user AUTO_INCREMENT = 1;

SET FOREIGN_KEY_CHECKS = 1;
