SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS reservation;
DROP TABLE IF EXISTS payment;
DROP TABLE IF EXISTS room;
DROP TABLE IF EXISTS customer;
DROP TABLE IF EXISTS staff;
DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS migrations;
DROP TABLE IF EXISTS product;
DROP TABLE IF EXISTS `review`;
DROP TABLE IF EXISTS `order`;
DROP TABLE IF EXISTS `discounts`;
SET FOREIGN_KEY_CHECKS = 1;
