import type { Metadata } from 'next'
import './globals.css'

import { GeistSans } from 'geist/font/sans'

import Header from '@/components/header'
import Footer from '@/components/footer'
import Providers from '@/components/provider' // <- Your new wrapper

export const metadata: Metadata = {
  title: 'Harmony House - KTV and Bar',
  description: 'Generated by create next app',
  icons: {
    icon: '/images/harmony-house-logo.png',
  },
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className={`${GeistSans.className} `}>
        <Providers>
          <Header />
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  )
}
