// app/layout.tsx
import type { Metadata } from 'next'
import './globals.css'
import { GeistSans } from 'geist/font/sans'

import Providers from '@/components/provider'
import LayoutWrapper from '@/components/layout-wrapper' // <-- use wrapper

export const metadata: Metadata = {
  title: 'Harmony House - KTV and Bar',
  description: 'Generated by create next app',
  icons: {
    icon: '/images/harmony-house-logo.png',
  },
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <body className={GeistSans.className}>
        <Providers>
          <LayoutWrapper>{children}</LayoutWrapper>
        </Providers>
      </body>
    </html>
  )
}
